"""Add on delete for MR FK constraint

Revision ID: a517ce3b246a
Revises: e93d0123c41f
Create Date: 2023-05-24 07:13:06.777431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a517ce3b246a'
down_revision = 'e93d0123c41f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BindUser_room_uuid_fkey', 'BindUser', type_='foreignkey')
    op.create_foreign_key(None, 'BindUser', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.drop_constraint('GR_Member_group_uuid_fkey', 'GR_Member', type_='foreignkey')
    op.create_foreign_key(None, 'GR_Member', 'Group', ['group_uuid'], ['group_uuid'], ondelete='CASCADE')
    op.alter_column('Group', 'room_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('Group_room_uuid_fkey', 'Group', type_='foreignkey')
    op.create_foreign_key(None, 'Group', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='SET NULL')
    op.drop_constraint('MR_Liked_Hated_Member_room_uuid_fkey', 'MR_Liked_Hated_Member', type_='foreignkey')
    op.create_foreign_key(None, 'MR_Liked_Hated_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'MR_Member', ['member_id'])
    op.drop_constraint('MR_Member_user_uuid_fkey', 'MR_Member', type_='foreignkey')
    op.drop_constraint('MR_Member_room_uuid_fkey', 'MR_Member', type_='foreignkey')
    op.create_foreign_key(None, 'MR_Member', 'User', ['user_uuid'], ['user_uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'MR_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.drop_constraint('MR_Member_Tag_room_uuid_fkey', 'MR_Member_Tag', type_='foreignkey')
    op.create_foreign_key(None, 'MR_Member_Tag', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.drop_constraint('MR_Rcmed_Member_room_uuid_fkey', 'MR_Rcmed_Member', type_='foreignkey')
    op.create_foreign_key(None, 'MR_Rcmed_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.drop_constraint('MatchingEvent_room_uuid_fkey', 'MatchingEvent', type_='foreignkey')
    op.create_foreign_key(None, 'MatchingEvent', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    op.drop_constraint('NotificationTemplate_template_id_key', 'NotificationTemplate', type_='unique')
    op.drop_constraint('Tag_room_uuid_fkey', 'Tag', type_='foreignkey')
    op.create_foreign_key(None, 'Tag', 'MatchingRoom', ['room_uuid'], ['room_uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tag', type_='foreignkey')
    op.create_foreign_key('Tag_room_uuid_fkey', 'Tag', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.create_unique_constraint('NotificationTemplate_template_id_key', 'NotificationTemplate', ['template_id'])
    op.drop_constraint(None, 'MatchingEvent', type_='foreignkey')
    op.create_foreign_key('MatchingEvent_room_uuid_fkey', 'MatchingEvent', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.drop_constraint(None, 'MR_Rcmed_Member', type_='foreignkey')
    op.create_foreign_key('MR_Rcmed_Member_room_uuid_fkey', 'MR_Rcmed_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.drop_constraint(None, 'MR_Member_Tag', type_='foreignkey')
    op.create_foreign_key('MR_Member_Tag_room_uuid_fkey', 'MR_Member_Tag', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.drop_constraint(None, 'MR_Member', type_='foreignkey')
    op.drop_constraint(None, 'MR_Member', type_='foreignkey')
    op.create_foreign_key('MR_Member_room_uuid_fkey', 'MR_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.create_foreign_key('MR_Member_user_uuid_fkey', 'MR_Member', 'User', ['user_uuid'], ['user_uuid'])
    op.drop_constraint(None, 'MR_Member', type_='unique')
    op.drop_constraint(None, 'MR_Liked_Hated_Member', type_='foreignkey')
    op.create_foreign_key('MR_Liked_Hated_Member_room_uuid_fkey', 'MR_Liked_Hated_Member', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.drop_constraint(None, 'Group', type_='foreignkey')
    op.create_foreign_key('Group_room_uuid_fkey', 'Group', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    op.alter_column('Group', 'room_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'GR_Member', type_='foreignkey')
    op.create_foreign_key('GR_Member_group_uuid_fkey', 'GR_Member', 'Group', ['group_uuid'], ['group_uuid'])
    op.drop_constraint(None, 'BindUser', type_='foreignkey')
    op.create_foreign_key('BindUser_room_uuid_fkey', 'BindUser', 'MatchingRoom', ['room_uuid'], ['room_uuid'])
    # ### end Alembic commands ###
