FROM teamatch_backend:latest
WORKDIR /backend
CMD ["python","microservices/scheduler/server.py"]

# CMD ["python", "-m", "uvicorn", "--host", "0.0.0.0", "--port", "8003", "microservices.scheduler.main:app", "--reload"]